name: Handle-incoming-issues-with-repository
on: issues
#this issues is an event trigger, an officially supported event
jobs:
  job-to-output-information:
    runs-on: ubuntu-latest
    steps:
      - name: output the event details from github metadata
        #run: echo "${{ toJSON(github.event) }}"
        #note github.event and not all of the data "github"
        # github.event is wrapped in toJSON function
        # event is nested inside the github object as shown in other yml
        run: |
         echo "${{ toJSON(github.event.user) }}"
         echo "${{ toJSON(github.event.repository) }}"